// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dna.proto

#ifndef PROTOBUF_dna_2eproto__INCLUDED
#define PROTOBUF_dna_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace RemyBuffers {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dna_2eproto();
void protobuf_AssignDesc_dna_2eproto();
void protobuf_ShutdownFile_dna_2eproto();

class WhiskerTree;
class MemoryRange;
class Memory;
class Whisker;
class OptimizationSetting;
class OptimizationSettings;
class Range;
class ConfigRange;
class NetConfig;

// ===================================================================

class WhiskerTree : public ::google::protobuf::Message {
 public:
  WhiskerTree();
  virtual ~WhiskerTree();
  
  WhiskerTree(const WhiskerTree& from);
  
  inline WhiskerTree& operator=(const WhiskerTree& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const WhiskerTree& default_instance();
  
  void Swap(WhiskerTree* other);
  
  // implements Message ----------------------------------------------
  
  WhiskerTree* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WhiskerTree& from);
  void MergeFrom(const WhiskerTree& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .RemyBuffers.MemoryRange domain = 1;
  inline bool has_domain() const;
  inline void clear_domain();
  static const int kDomainFieldNumber = 1;
  inline const ::RemyBuffers::MemoryRange& domain() const;
  inline ::RemyBuffers::MemoryRange* mutable_domain();
  inline ::RemyBuffers::MemoryRange* release_domain();
  
  // repeated .RemyBuffers.WhiskerTree children = 2;
  inline int children_size() const;
  inline void clear_children();
  static const int kChildrenFieldNumber = 2;
  inline const ::RemyBuffers::WhiskerTree& children(int index) const;
  inline ::RemyBuffers::WhiskerTree* mutable_children(int index);
  inline ::RemyBuffers::WhiskerTree* add_children();
  inline const ::google::protobuf::RepeatedPtrField< ::RemyBuffers::WhiskerTree >&
      children() const;
  inline ::google::protobuf::RepeatedPtrField< ::RemyBuffers::WhiskerTree >*
      mutable_children();
  
  // optional .RemyBuffers.Whisker leaf = 3;
  inline bool has_leaf() const;
  inline void clear_leaf();
  static const int kLeafFieldNumber = 3;
  inline const ::RemyBuffers::Whisker& leaf() const;
  inline ::RemyBuffers::Whisker* mutable_leaf();
  inline ::RemyBuffers::Whisker* release_leaf();
  
  // optional .RemyBuffers.ConfigRange config = 4;
  inline bool has_config() const;
  inline void clear_config();
  static const int kConfigFieldNumber = 4;
  inline const ::RemyBuffers::ConfigRange& config() const;
  inline ::RemyBuffers::ConfigRange* mutable_config();
  inline ::RemyBuffers::ConfigRange* release_config();
  
  // optional .RemyBuffers.OptimizationSettings optimizer = 5;
  inline bool has_optimizer() const;
  inline void clear_optimizer();
  static const int kOptimizerFieldNumber = 5;
  inline const ::RemyBuffers::OptimizationSettings& optimizer() const;
  inline ::RemyBuffers::OptimizationSettings* mutable_optimizer();
  inline ::RemyBuffers::OptimizationSettings* release_optimizer();
  
  // @@protoc_insertion_point(class_scope:RemyBuffers.WhiskerTree)
 private:
  inline void set_has_domain();
  inline void clear_has_domain();
  inline void set_has_leaf();
  inline void clear_has_leaf();
  inline void set_has_config();
  inline void clear_has_config();
  inline void set_has_optimizer();
  inline void clear_has_optimizer();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::RemyBuffers::MemoryRange* domain_;
  ::google::protobuf::RepeatedPtrField< ::RemyBuffers::WhiskerTree > children_;
  ::RemyBuffers::Whisker* leaf_;
  ::RemyBuffers::ConfigRange* config_;
  ::RemyBuffers::OptimizationSettings* optimizer_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_dna_2eproto();
  friend void protobuf_AssignDesc_dna_2eproto();
  friend void protobuf_ShutdownFile_dna_2eproto();
  
  void InitAsDefaultInstance();
  static WhiskerTree* default_instance_;
};
// -------------------------------------------------------------------

class MemoryRange : public ::google::protobuf::Message {
 public:
  MemoryRange();
  virtual ~MemoryRange();
  
  MemoryRange(const MemoryRange& from);
  
  inline MemoryRange& operator=(const MemoryRange& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MemoryRange& default_instance();
  
  void Swap(MemoryRange* other);
  
  // implements Message ----------------------------------------------
  
  MemoryRange* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MemoryRange& from);
  void MergeFrom(const MemoryRange& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .RemyBuffers.Memory lower = 11;
  inline bool has_lower() const;
  inline void clear_lower();
  static const int kLowerFieldNumber = 11;
  inline const ::RemyBuffers::Memory& lower() const;
  inline ::RemyBuffers::Memory* mutable_lower();
  inline ::RemyBuffers::Memory* release_lower();
  
  // optional .RemyBuffers.Memory upper = 12;
  inline bool has_upper() const;
  inline void clear_upper();
  static const int kUpperFieldNumber = 12;
  inline const ::RemyBuffers::Memory& upper() const;
  inline ::RemyBuffers::Memory* mutable_upper();
  inline ::RemyBuffers::Memory* release_upper();
  
  // @@protoc_insertion_point(class_scope:RemyBuffers.MemoryRange)
 private:
  inline void set_has_lower();
  inline void clear_has_lower();
  inline void set_has_upper();
  inline void clear_has_upper();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::RemyBuffers::Memory* lower_;
  ::RemyBuffers::Memory* upper_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_dna_2eproto();
  friend void protobuf_AssignDesc_dna_2eproto();
  friend void protobuf_ShutdownFile_dna_2eproto();
  
  void InitAsDefaultInstance();
  static MemoryRange* default_instance_;
};
// -------------------------------------------------------------------

class Memory : public ::google::protobuf::Message {
 public:
  Memory();
  virtual ~Memory();
  
  Memory(const Memory& from);
  
  inline Memory& operator=(const Memory& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Memory& default_instance();
  
  void Swap(Memory* other);
  
  // implements Message ----------------------------------------------
  
  Memory* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Memory& from);
  void MergeFrom(const Memory& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional double rec_send_ewma = 21;
  inline bool has_rec_send_ewma() const;
  inline void clear_rec_send_ewma();
  static const int kRecSendEwmaFieldNumber = 21;
  inline double rec_send_ewma() const;
  inline void set_rec_send_ewma(double value);
  
  // optional double rec_rec_ewma = 22;
  inline bool has_rec_rec_ewma() const;
  inline void clear_rec_rec_ewma();
  static const int kRecRecEwmaFieldNumber = 22;
  inline double rec_rec_ewma() const;
  inline void set_rec_rec_ewma(double value);
  
  // optional double rtt_ratio = 23;
  inline bool has_rtt_ratio() const;
  inline void clear_rtt_ratio();
  static const int kRttRatioFieldNumber = 23;
  inline double rtt_ratio() const;
  inline void set_rtt_ratio(double value);
  
  // optional double slow_rec_rec_ewma = 24;
  inline bool has_slow_rec_rec_ewma() const;
  inline void clear_slow_rec_rec_ewma();
  static const int kSlowRecRecEwmaFieldNumber = 24;
  inline double slow_rec_rec_ewma() const;
  inline void set_slow_rec_rec_ewma(double value);
  
  // @@protoc_insertion_point(class_scope:RemyBuffers.Memory)
 private:
  inline void set_has_rec_send_ewma();
  inline void clear_has_rec_send_ewma();
  inline void set_has_rec_rec_ewma();
  inline void clear_has_rec_rec_ewma();
  inline void set_has_rtt_ratio();
  inline void clear_has_rtt_ratio();
  inline void set_has_slow_rec_rec_ewma();
  inline void clear_has_slow_rec_rec_ewma();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  double rec_send_ewma_;
  double rec_rec_ewma_;
  double rtt_ratio_;
  double slow_rec_rec_ewma_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_dna_2eproto();
  friend void protobuf_AssignDesc_dna_2eproto();
  friend void protobuf_ShutdownFile_dna_2eproto();
  
  void InitAsDefaultInstance();
  static Memory* default_instance_;
};
// -------------------------------------------------------------------

class Whisker : public ::google::protobuf::Message {
 public:
  Whisker();
  virtual ~Whisker();
  
  Whisker(const Whisker& from);
  
  inline Whisker& operator=(const Whisker& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Whisker& default_instance();
  
  void Swap(Whisker* other);
  
  // implements Message ----------------------------------------------
  
  Whisker* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Whisker& from);
  void MergeFrom(const Whisker& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional sint32 window_increment = 31;
  inline bool has_window_increment() const;
  inline void clear_window_increment();
  static const int kWindowIncrementFieldNumber = 31;
  inline ::google::protobuf::int32 window_increment() const;
  inline void set_window_increment(::google::protobuf::int32 value);
  
  // optional double window_multiple = 32;
  inline bool has_window_multiple() const;
  inline void clear_window_multiple();
  static const int kWindowMultipleFieldNumber = 32;
  inline double window_multiple() const;
  inline void set_window_multiple(double value);
  
  // optional double intersend = 33;
  inline bool has_intersend() const;
  inline void clear_intersend();
  static const int kIntersendFieldNumber = 33;
  inline double intersend() const;
  inline void set_intersend(double value);
  
  // optional .RemyBuffers.MemoryRange domain = 34;
  inline bool has_domain() const;
  inline void clear_domain();
  static const int kDomainFieldNumber = 34;
  inline const ::RemyBuffers::MemoryRange& domain() const;
  inline ::RemyBuffers::MemoryRange* mutable_domain();
  inline ::RemyBuffers::MemoryRange* release_domain();
  
  // @@protoc_insertion_point(class_scope:RemyBuffers.Whisker)
 private:
  inline void set_has_window_increment();
  inline void clear_has_window_increment();
  inline void set_has_window_multiple();
  inline void clear_has_window_multiple();
  inline void set_has_intersend();
  inline void clear_has_intersend();
  inline void set_has_domain();
  inline void clear_has_domain();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  double window_multiple_;
  double intersend_;
  ::RemyBuffers::MemoryRange* domain_;
  ::google::protobuf::int32 window_increment_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_dna_2eproto();
  friend void protobuf_AssignDesc_dna_2eproto();
  friend void protobuf_ShutdownFile_dna_2eproto();
  
  void InitAsDefaultInstance();
  static Whisker* default_instance_;
};
// -------------------------------------------------------------------

class OptimizationSetting : public ::google::protobuf::Message {
 public:
  OptimizationSetting();
  virtual ~OptimizationSetting();
  
  OptimizationSetting(const OptimizationSetting& from);
  
  inline OptimizationSetting& operator=(const OptimizationSetting& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const OptimizationSetting& default_instance();
  
  void Swap(OptimizationSetting* other);
  
  // implements Message ----------------------------------------------
  
  OptimizationSetting* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OptimizationSetting& from);
  void MergeFrom(const OptimizationSetting& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional double min_value = 41;
  inline bool has_min_value() const;
  inline void clear_min_value();
  static const int kMinValueFieldNumber = 41;
  inline double min_value() const;
  inline void set_min_value(double value);
  
  // optional double max_value = 42;
  inline bool has_max_value() const;
  inline void clear_max_value();
  static const int kMaxValueFieldNumber = 42;
  inline double max_value() const;
  inline void set_max_value(double value);
  
  // optional double min_change = 43;
  inline bool has_min_change() const;
  inline void clear_min_change();
  static const int kMinChangeFieldNumber = 43;
  inline double min_change() const;
  inline void set_min_change(double value);
  
  // optional double max_change = 44;
  inline bool has_max_change() const;
  inline void clear_max_change();
  static const int kMaxChangeFieldNumber = 44;
  inline double max_change() const;
  inline void set_max_change(double value);
  
  // optional double multiplier = 45;
  inline bool has_multiplier() const;
  inline void clear_multiplier();
  static const int kMultiplierFieldNumber = 45;
  inline double multiplier() const;
  inline void set_multiplier(double value);
  
  // optional double default_value = 46;
  inline bool has_default_value() const;
  inline void clear_default_value();
  static const int kDefaultValueFieldNumber = 46;
  inline double default_value() const;
  inline void set_default_value(double value);
  
  // @@protoc_insertion_point(class_scope:RemyBuffers.OptimizationSetting)
 private:
  inline void set_has_min_value();
  inline void clear_has_min_value();
  inline void set_has_max_value();
  inline void clear_has_max_value();
  inline void set_has_min_change();
  inline void clear_has_min_change();
  inline void set_has_max_change();
  inline void clear_has_max_change();
  inline void set_has_multiplier();
  inline void clear_has_multiplier();
  inline void set_has_default_value();
  inline void clear_has_default_value();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  double min_value_;
  double max_value_;
  double min_change_;
  double max_change_;
  double multiplier_;
  double default_value_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void  protobuf_AddDesc_dna_2eproto();
  friend void protobuf_AssignDesc_dna_2eproto();
  friend void protobuf_ShutdownFile_dna_2eproto();
  
  void InitAsDefaultInstance();
  static OptimizationSetting* default_instance_;
};
// -------------------------------------------------------------------

class OptimizationSettings : public ::google::protobuf::Message {
 public:
  OptimizationSettings();
  virtual ~OptimizationSettings();
  
  OptimizationSettings(const OptimizationSettings& from);
  
  inline OptimizationSettings& operator=(const OptimizationSettings& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const OptimizationSettings& default_instance();
  
  void Swap(OptimizationSettings* other);
  
  // implements Message ----------------------------------------------
  
  OptimizationSettings* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OptimizationSettings& from);
  void MergeFrom(const OptimizationSettings& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .RemyBuffers.OptimizationSetting window_increment = 51;
  inline bool has_window_increment() const;
  inline void clear_window_increment();
  static const int kWindowIncrementFieldNumber = 51;
  inline const ::RemyBuffers::OptimizationSetting& window_increment() const;
  inline ::RemyBuffers::OptimizationSetting* mutable_window_increment();
  inline ::RemyBuffers::OptimizationSetting* release_window_increment();
  
  // optional .RemyBuffers.OptimizationSetting window_multiple = 52;
  inline bool has_window_multiple() const;
  inline void clear_window_multiple();
  static const int kWindowMultipleFieldNumber = 52;
  inline const ::RemyBuffers::OptimizationSetting& window_multiple() const;
  inline ::RemyBuffers::OptimizationSetting* mutable_window_multiple();
  inline ::RemyBuffers::OptimizationSetting* release_window_multiple();
  
  // optional .RemyBuffers.OptimizationSetting intersend = 53;
  inline bool has_intersend() const;
  inline void clear_intersend();
  static const int kIntersendFieldNumber = 53;
  inline const ::RemyBuffers::OptimizationSetting& intersend() const;
  inline ::RemyBuffers::OptimizationSetting* mutable_intersend();
  inline ::RemyBuffers::OptimizationSetting* release_intersend();
  
  // @@protoc_insertion_point(class_scope:RemyBuffers.OptimizationSettings)
 private:
  inline void set_has_window_increment();
  inline void clear_has_window_increment();
  inline void set_has_window_multiple();
  inline void clear_has_window_multiple();
  inline void set_has_intersend();
  inline void clear_has_intersend();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::RemyBuffers::OptimizationSetting* window_increment_;
  ::RemyBuffers::OptimizationSetting* window_multiple_;
  ::RemyBuffers::OptimizationSetting* intersend_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_dna_2eproto();
  friend void protobuf_AssignDesc_dna_2eproto();
  friend void protobuf_ShutdownFile_dna_2eproto();
  
  void InitAsDefaultInstance();
  static OptimizationSettings* default_instance_;
};
// -------------------------------------------------------------------

class Range : public ::google::protobuf::Message {
 public:
  Range();
  virtual ~Range();
  
  Range(const Range& from);
  
  inline Range& operator=(const Range& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Range& default_instance();
  
  void Swap(Range* other);
  
  // implements Message ----------------------------------------------
  
  Range* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Range& from);
  void MergeFrom(const Range& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional double low = 61;
  inline bool has_low() const;
  inline void clear_low();
  static const int kLowFieldNumber = 61;
  inline double low() const;
  inline void set_low(double value);
  
  // optional double high = 62;
  inline bool has_high() const;
  inline void clear_high();
  static const int kHighFieldNumber = 62;
  inline double high() const;
  inline void set_high(double value);
  
  // @@protoc_insertion_point(class_scope:RemyBuffers.Range)
 private:
  inline void set_has_low();
  inline void clear_has_low();
  inline void set_has_high();
  inline void clear_has_high();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  double low_;
  double high_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_dna_2eproto();
  friend void protobuf_AssignDesc_dna_2eproto();
  friend void protobuf_ShutdownFile_dna_2eproto();
  
  void InitAsDefaultInstance();
  static Range* default_instance_;
};
// -------------------------------------------------------------------

class ConfigRange : public ::google::protobuf::Message {
 public:
  ConfigRange();
  virtual ~ConfigRange();
  
  ConfigRange(const ConfigRange& from);
  
  inline ConfigRange& operator=(const ConfigRange& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfigRange& default_instance();
  
  void Swap(ConfigRange* other);
  
  // implements Message ----------------------------------------------
  
  ConfigRange* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConfigRange& from);
  void MergeFrom(const ConfigRange& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .RemyBuffers.Range link_packets_per_ms = 71;
  inline bool has_link_packets_per_ms() const;
  inline void clear_link_packets_per_ms();
  static const int kLinkPacketsPerMsFieldNumber = 71;
  inline const ::RemyBuffers::Range& link_packets_per_ms() const;
  inline ::RemyBuffers::Range* mutable_link_packets_per_ms();
  inline ::RemyBuffers::Range* release_link_packets_per_ms();
  
  // optional .RemyBuffers.Range rtt = 72;
  inline bool has_rtt() const;
  inline void clear_rtt();
  static const int kRttFieldNumber = 72;
  inline const ::RemyBuffers::Range& rtt() const;
  inline ::RemyBuffers::Range* mutable_rtt();
  inline ::RemyBuffers::Range* release_rtt();
  
  // optional .RemyBuffers.Range num_senders = 73;
  inline bool has_num_senders() const;
  inline void clear_num_senders();
  static const int kNumSendersFieldNumber = 73;
  inline const ::RemyBuffers::Range& num_senders() const;
  inline ::RemyBuffers::Range* mutable_num_senders();
  inline ::RemyBuffers::Range* release_num_senders();
  
  // optional double mean_off_duration = 81;
  inline bool has_mean_off_duration() const;
  inline void clear_mean_off_duration();
  static const int kMeanOffDurationFieldNumber = 81;
  inline double mean_off_duration() const;
  inline void set_mean_off_duration(double value);
  
  // optional double mean_on_duration = 82;
  inline bool has_mean_on_duration() const;
  inline void clear_mean_on_duration();
  static const int kMeanOnDurationFieldNumber = 82;
  inline double mean_on_duration() const;
  inline void set_mean_on_duration(double value);
  
  // @@protoc_insertion_point(class_scope:RemyBuffers.ConfigRange)
 private:
  inline void set_has_link_packets_per_ms();
  inline void clear_has_link_packets_per_ms();
  inline void set_has_rtt();
  inline void clear_has_rtt();
  inline void set_has_num_senders();
  inline void clear_has_num_senders();
  inline void set_has_mean_off_duration();
  inline void clear_has_mean_off_duration();
  inline void set_has_mean_on_duration();
  inline void clear_has_mean_on_duration();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::RemyBuffers::Range* link_packets_per_ms_;
  ::RemyBuffers::Range* rtt_;
  ::RemyBuffers::Range* num_senders_;
  double mean_off_duration_;
  double mean_on_duration_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_dna_2eproto();
  friend void protobuf_AssignDesc_dna_2eproto();
  friend void protobuf_ShutdownFile_dna_2eproto();
  
  void InitAsDefaultInstance();
  static ConfigRange* default_instance_;
};
// -------------------------------------------------------------------

class NetConfig : public ::google::protobuf::Message {
 public:
  NetConfig();
  virtual ~NetConfig();
  
  NetConfig(const NetConfig& from);
  
  inline NetConfig& operator=(const NetConfig& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const NetConfig& default_instance();
  
  void Swap(NetConfig* other);
  
  // implements Message ----------------------------------------------
  
  NetConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NetConfig& from);
  void MergeFrom(const NetConfig& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional double mean_on_duration = 1;
  inline bool has_mean_on_duration() const;
  inline void clear_mean_on_duration();
  static const int kMeanOnDurationFieldNumber = 1;
  inline double mean_on_duration() const;
  inline void set_mean_on_duration(double value);
  
  // optional double mean_off_duration = 2;
  inline bool has_mean_off_duration() const;
  inline void clear_mean_off_duration();
  static const int kMeanOffDurationFieldNumber = 2;
  inline double mean_off_duration() const;
  inline void set_mean_off_duration(double value);
  
  // optional uint32 num_senders = 3;
  inline bool has_num_senders() const;
  inline void clear_num_senders();
  static const int kNumSendersFieldNumber = 3;
  inline ::google::protobuf::uint32 num_senders() const;
  inline void set_num_senders(::google::protobuf::uint32 value);
  
  // optional double link_ppt = 4;
  inline bool has_link_ppt() const;
  inline void clear_link_ppt();
  static const int kLinkPptFieldNumber = 4;
  inline double link_ppt() const;
  inline void set_link_ppt(double value);
  
  // optional double delay = 5;
  inline bool has_delay() const;
  inline void clear_delay();
  static const int kDelayFieldNumber = 5;
  inline double delay() const;
  inline void set_delay(double value);
  
  // @@protoc_insertion_point(class_scope:RemyBuffers.NetConfig)
 private:
  inline void set_has_mean_on_duration();
  inline void clear_has_mean_on_duration();
  inline void set_has_mean_off_duration();
  inline void clear_has_mean_off_duration();
  inline void set_has_num_senders();
  inline void clear_has_num_senders();
  inline void set_has_link_ppt();
  inline void clear_has_link_ppt();
  inline void set_has_delay();
  inline void clear_has_delay();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  double mean_on_duration_;
  double mean_off_duration_;
  double link_ppt_;
  double delay_;
  ::google::protobuf::uint32 num_senders_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_dna_2eproto();
  friend void protobuf_AssignDesc_dna_2eproto();
  friend void protobuf_ShutdownFile_dna_2eproto();
  
  void InitAsDefaultInstance();
  static NetConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// WhiskerTree

// optional .RemyBuffers.MemoryRange domain = 1;
inline bool WhiskerTree::has_domain() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WhiskerTree::set_has_domain() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WhiskerTree::clear_has_domain() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WhiskerTree::clear_domain() {
  if (domain_ != NULL) domain_->::RemyBuffers::MemoryRange::Clear();
  clear_has_domain();
}
inline const ::RemyBuffers::MemoryRange& WhiskerTree::domain() const {
  return domain_ != NULL ? *domain_ : *default_instance_->domain_;
}
inline ::RemyBuffers::MemoryRange* WhiskerTree::mutable_domain() {
  set_has_domain();
  if (domain_ == NULL) domain_ = new ::RemyBuffers::MemoryRange;
  return domain_;
}
inline ::RemyBuffers::MemoryRange* WhiskerTree::release_domain() {
  clear_has_domain();
  ::RemyBuffers::MemoryRange* temp = domain_;
  domain_ = NULL;
  return temp;
}

// repeated .RemyBuffers.WhiskerTree children = 2;
inline int WhiskerTree::children_size() const {
  return children_.size();
}
inline void WhiskerTree::clear_children() {
  children_.Clear();
}
inline const ::RemyBuffers::WhiskerTree& WhiskerTree::children(int index) const {
  return children_.Get(index);
}
inline ::RemyBuffers::WhiskerTree* WhiskerTree::mutable_children(int index) {
  return children_.Mutable(index);
}
inline ::RemyBuffers::WhiskerTree* WhiskerTree::add_children() {
  return children_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::RemyBuffers::WhiskerTree >&
WhiskerTree::children() const {
  return children_;
}
inline ::google::protobuf::RepeatedPtrField< ::RemyBuffers::WhiskerTree >*
WhiskerTree::mutable_children() {
  return &children_;
}

// optional .RemyBuffers.Whisker leaf = 3;
inline bool WhiskerTree::has_leaf() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WhiskerTree::set_has_leaf() {
  _has_bits_[0] |= 0x00000004u;
}
inline void WhiskerTree::clear_has_leaf() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void WhiskerTree::clear_leaf() {
  if (leaf_ != NULL) leaf_->::RemyBuffers::Whisker::Clear();
  clear_has_leaf();
}
inline const ::RemyBuffers::Whisker& WhiskerTree::leaf() const {
  return leaf_ != NULL ? *leaf_ : *default_instance_->leaf_;
}
inline ::RemyBuffers::Whisker* WhiskerTree::mutable_leaf() {
  set_has_leaf();
  if (leaf_ == NULL) leaf_ = new ::RemyBuffers::Whisker;
  return leaf_;
}
inline ::RemyBuffers::Whisker* WhiskerTree::release_leaf() {
  clear_has_leaf();
  ::RemyBuffers::Whisker* temp = leaf_;
  leaf_ = NULL;
  return temp;
}

// optional .RemyBuffers.ConfigRange config = 4;
inline bool WhiskerTree::has_config() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void WhiskerTree::set_has_config() {
  _has_bits_[0] |= 0x00000008u;
}
inline void WhiskerTree::clear_has_config() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void WhiskerTree::clear_config() {
  if (config_ != NULL) config_->::RemyBuffers::ConfigRange::Clear();
  clear_has_config();
}
inline const ::RemyBuffers::ConfigRange& WhiskerTree::config() const {
  return config_ != NULL ? *config_ : *default_instance_->config_;
}
inline ::RemyBuffers::ConfigRange* WhiskerTree::mutable_config() {
  set_has_config();
  if (config_ == NULL) config_ = new ::RemyBuffers::ConfigRange;
  return config_;
}
inline ::RemyBuffers::ConfigRange* WhiskerTree::release_config() {
  clear_has_config();
  ::RemyBuffers::ConfigRange* temp = config_;
  config_ = NULL;
  return temp;
}

// optional .RemyBuffers.OptimizationSettings optimizer = 5;
inline bool WhiskerTree::has_optimizer() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void WhiskerTree::set_has_optimizer() {
  _has_bits_[0] |= 0x00000010u;
}
inline void WhiskerTree::clear_has_optimizer() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void WhiskerTree::clear_optimizer() {
  if (optimizer_ != NULL) optimizer_->::RemyBuffers::OptimizationSettings::Clear();
  clear_has_optimizer();
}
inline const ::RemyBuffers::OptimizationSettings& WhiskerTree::optimizer() const {
  return optimizer_ != NULL ? *optimizer_ : *default_instance_->optimizer_;
}
inline ::RemyBuffers::OptimizationSettings* WhiskerTree::mutable_optimizer() {
  set_has_optimizer();
  if (optimizer_ == NULL) optimizer_ = new ::RemyBuffers::OptimizationSettings;
  return optimizer_;
}
inline ::RemyBuffers::OptimizationSettings* WhiskerTree::release_optimizer() {
  clear_has_optimizer();
  ::RemyBuffers::OptimizationSettings* temp = optimizer_;
  optimizer_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// MemoryRange

// optional .RemyBuffers.Memory lower = 11;
inline bool MemoryRange::has_lower() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MemoryRange::set_has_lower() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MemoryRange::clear_has_lower() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MemoryRange::clear_lower() {
  if (lower_ != NULL) lower_->::RemyBuffers::Memory::Clear();
  clear_has_lower();
}
inline const ::RemyBuffers::Memory& MemoryRange::lower() const {
  return lower_ != NULL ? *lower_ : *default_instance_->lower_;
}
inline ::RemyBuffers::Memory* MemoryRange::mutable_lower() {
  set_has_lower();
  if (lower_ == NULL) lower_ = new ::RemyBuffers::Memory;
  return lower_;
}
inline ::RemyBuffers::Memory* MemoryRange::release_lower() {
  clear_has_lower();
  ::RemyBuffers::Memory* temp = lower_;
  lower_ = NULL;
  return temp;
}

// optional .RemyBuffers.Memory upper = 12;
inline bool MemoryRange::has_upper() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MemoryRange::set_has_upper() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MemoryRange::clear_has_upper() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MemoryRange::clear_upper() {
  if (upper_ != NULL) upper_->::RemyBuffers::Memory::Clear();
  clear_has_upper();
}
inline const ::RemyBuffers::Memory& MemoryRange::upper() const {
  return upper_ != NULL ? *upper_ : *default_instance_->upper_;
}
inline ::RemyBuffers::Memory* MemoryRange::mutable_upper() {
  set_has_upper();
  if (upper_ == NULL) upper_ = new ::RemyBuffers::Memory;
  return upper_;
}
inline ::RemyBuffers::Memory* MemoryRange::release_upper() {
  clear_has_upper();
  ::RemyBuffers::Memory* temp = upper_;
  upper_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// Memory

// optional double rec_send_ewma = 21;
inline bool Memory::has_rec_send_ewma() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Memory::set_has_rec_send_ewma() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Memory::clear_has_rec_send_ewma() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Memory::clear_rec_send_ewma() {
  rec_send_ewma_ = 0;
  clear_has_rec_send_ewma();
}
inline double Memory::rec_send_ewma() const {
  return rec_send_ewma_;
}
inline void Memory::set_rec_send_ewma(double value) {
  set_has_rec_send_ewma();
  rec_send_ewma_ = value;
}

// optional double rec_rec_ewma = 22;
inline bool Memory::has_rec_rec_ewma() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Memory::set_has_rec_rec_ewma() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Memory::clear_has_rec_rec_ewma() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Memory::clear_rec_rec_ewma() {
  rec_rec_ewma_ = 0;
  clear_has_rec_rec_ewma();
}
inline double Memory::rec_rec_ewma() const {
  return rec_rec_ewma_;
}
inline void Memory::set_rec_rec_ewma(double value) {
  set_has_rec_rec_ewma();
  rec_rec_ewma_ = value;
}

// optional double rtt_ratio = 23;
inline bool Memory::has_rtt_ratio() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Memory::set_has_rtt_ratio() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Memory::clear_has_rtt_ratio() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Memory::clear_rtt_ratio() {
  rtt_ratio_ = 0;
  clear_has_rtt_ratio();
}
inline double Memory::rtt_ratio() const {
  return rtt_ratio_;
}
inline void Memory::set_rtt_ratio(double value) {
  set_has_rtt_ratio();
  rtt_ratio_ = value;
}

// optional double slow_rec_rec_ewma = 24;
inline bool Memory::has_slow_rec_rec_ewma() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Memory::set_has_slow_rec_rec_ewma() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Memory::clear_has_slow_rec_rec_ewma() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Memory::clear_slow_rec_rec_ewma() {
  slow_rec_rec_ewma_ = 0;
  clear_has_slow_rec_rec_ewma();
}
inline double Memory::slow_rec_rec_ewma() const {
  return slow_rec_rec_ewma_;
}
inline void Memory::set_slow_rec_rec_ewma(double value) {
  set_has_slow_rec_rec_ewma();
  slow_rec_rec_ewma_ = value;
}

// -------------------------------------------------------------------

// Whisker

// optional sint32 window_increment = 31;
inline bool Whisker::has_window_increment() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Whisker::set_has_window_increment() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Whisker::clear_has_window_increment() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Whisker::clear_window_increment() {
  window_increment_ = 0;
  clear_has_window_increment();
}
inline ::google::protobuf::int32 Whisker::window_increment() const {
  return window_increment_;
}
inline void Whisker::set_window_increment(::google::protobuf::int32 value) {
  set_has_window_increment();
  window_increment_ = value;
}

// optional double window_multiple = 32;
inline bool Whisker::has_window_multiple() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Whisker::set_has_window_multiple() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Whisker::clear_has_window_multiple() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Whisker::clear_window_multiple() {
  window_multiple_ = 0;
  clear_has_window_multiple();
}
inline double Whisker::window_multiple() const {
  return window_multiple_;
}
inline void Whisker::set_window_multiple(double value) {
  set_has_window_multiple();
  window_multiple_ = value;
}

// optional double intersend = 33;
inline bool Whisker::has_intersend() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Whisker::set_has_intersend() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Whisker::clear_has_intersend() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Whisker::clear_intersend() {
  intersend_ = 0;
  clear_has_intersend();
}
inline double Whisker::intersend() const {
  return intersend_;
}
inline void Whisker::set_intersend(double value) {
  set_has_intersend();
  intersend_ = value;
}

// optional .RemyBuffers.MemoryRange domain = 34;
inline bool Whisker::has_domain() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Whisker::set_has_domain() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Whisker::clear_has_domain() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Whisker::clear_domain() {
  if (domain_ != NULL) domain_->::RemyBuffers::MemoryRange::Clear();
  clear_has_domain();
}
inline const ::RemyBuffers::MemoryRange& Whisker::domain() const {
  return domain_ != NULL ? *domain_ : *default_instance_->domain_;
}
inline ::RemyBuffers::MemoryRange* Whisker::mutable_domain() {
  set_has_domain();
  if (domain_ == NULL) domain_ = new ::RemyBuffers::MemoryRange;
  return domain_;
}
inline ::RemyBuffers::MemoryRange* Whisker::release_domain() {
  clear_has_domain();
  ::RemyBuffers::MemoryRange* temp = domain_;
  domain_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// OptimizationSetting

// optional double min_value = 41;
inline bool OptimizationSetting::has_min_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OptimizationSetting::set_has_min_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OptimizationSetting::clear_has_min_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OptimizationSetting::clear_min_value() {
  min_value_ = 0;
  clear_has_min_value();
}
inline double OptimizationSetting::min_value() const {
  return min_value_;
}
inline void OptimizationSetting::set_min_value(double value) {
  set_has_min_value();
  min_value_ = value;
}

// optional double max_value = 42;
inline bool OptimizationSetting::has_max_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OptimizationSetting::set_has_max_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OptimizationSetting::clear_has_max_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OptimizationSetting::clear_max_value() {
  max_value_ = 0;
  clear_has_max_value();
}
inline double OptimizationSetting::max_value() const {
  return max_value_;
}
inline void OptimizationSetting::set_max_value(double value) {
  set_has_max_value();
  max_value_ = value;
}

// optional double min_change = 43;
inline bool OptimizationSetting::has_min_change() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OptimizationSetting::set_has_min_change() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OptimizationSetting::clear_has_min_change() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OptimizationSetting::clear_min_change() {
  min_change_ = 0;
  clear_has_min_change();
}
inline double OptimizationSetting::min_change() const {
  return min_change_;
}
inline void OptimizationSetting::set_min_change(double value) {
  set_has_min_change();
  min_change_ = value;
}

// optional double max_change = 44;
inline bool OptimizationSetting::has_max_change() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OptimizationSetting::set_has_max_change() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OptimizationSetting::clear_has_max_change() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OptimizationSetting::clear_max_change() {
  max_change_ = 0;
  clear_has_max_change();
}
inline double OptimizationSetting::max_change() const {
  return max_change_;
}
inline void OptimizationSetting::set_max_change(double value) {
  set_has_max_change();
  max_change_ = value;
}

// optional double multiplier = 45;
inline bool OptimizationSetting::has_multiplier() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OptimizationSetting::set_has_multiplier() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OptimizationSetting::clear_has_multiplier() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OptimizationSetting::clear_multiplier() {
  multiplier_ = 0;
  clear_has_multiplier();
}
inline double OptimizationSetting::multiplier() const {
  return multiplier_;
}
inline void OptimizationSetting::set_multiplier(double value) {
  set_has_multiplier();
  multiplier_ = value;
}

// optional double default_value = 46;
inline bool OptimizationSetting::has_default_value() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void OptimizationSetting::set_has_default_value() {
  _has_bits_[0] |= 0x00000020u;
}
inline void OptimizationSetting::clear_has_default_value() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void OptimizationSetting::clear_default_value() {
  default_value_ = 0;
  clear_has_default_value();
}
inline double OptimizationSetting::default_value() const {
  return default_value_;
}
inline void OptimizationSetting::set_default_value(double value) {
  set_has_default_value();
  default_value_ = value;
}

// -------------------------------------------------------------------

// OptimizationSettings

// optional .RemyBuffers.OptimizationSetting window_increment = 51;
inline bool OptimizationSettings::has_window_increment() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OptimizationSettings::set_has_window_increment() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OptimizationSettings::clear_has_window_increment() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OptimizationSettings::clear_window_increment() {
  if (window_increment_ != NULL) window_increment_->::RemyBuffers::OptimizationSetting::Clear();
  clear_has_window_increment();
}
inline const ::RemyBuffers::OptimizationSetting& OptimizationSettings::window_increment() const {
  return window_increment_ != NULL ? *window_increment_ : *default_instance_->window_increment_;
}
inline ::RemyBuffers::OptimizationSetting* OptimizationSettings::mutable_window_increment() {
  set_has_window_increment();
  if (window_increment_ == NULL) window_increment_ = new ::RemyBuffers::OptimizationSetting;
  return window_increment_;
}
inline ::RemyBuffers::OptimizationSetting* OptimizationSettings::release_window_increment() {
  clear_has_window_increment();
  ::RemyBuffers::OptimizationSetting* temp = window_increment_;
  window_increment_ = NULL;
  return temp;
}

// optional .RemyBuffers.OptimizationSetting window_multiple = 52;
inline bool OptimizationSettings::has_window_multiple() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OptimizationSettings::set_has_window_multiple() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OptimizationSettings::clear_has_window_multiple() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OptimizationSettings::clear_window_multiple() {
  if (window_multiple_ != NULL) window_multiple_->::RemyBuffers::OptimizationSetting::Clear();
  clear_has_window_multiple();
}
inline const ::RemyBuffers::OptimizationSetting& OptimizationSettings::window_multiple() const {
  return window_multiple_ != NULL ? *window_multiple_ : *default_instance_->window_multiple_;
}
inline ::RemyBuffers::OptimizationSetting* OptimizationSettings::mutable_window_multiple() {
  set_has_window_multiple();
  if (window_multiple_ == NULL) window_multiple_ = new ::RemyBuffers::OptimizationSetting;
  return window_multiple_;
}
inline ::RemyBuffers::OptimizationSetting* OptimizationSettings::release_window_multiple() {
  clear_has_window_multiple();
  ::RemyBuffers::OptimizationSetting* temp = window_multiple_;
  window_multiple_ = NULL;
  return temp;
}

// optional .RemyBuffers.OptimizationSetting intersend = 53;
inline bool OptimizationSettings::has_intersend() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OptimizationSettings::set_has_intersend() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OptimizationSettings::clear_has_intersend() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OptimizationSettings::clear_intersend() {
  if (intersend_ != NULL) intersend_->::RemyBuffers::OptimizationSetting::Clear();
  clear_has_intersend();
}
inline const ::RemyBuffers::OptimizationSetting& OptimizationSettings::intersend() const {
  return intersend_ != NULL ? *intersend_ : *default_instance_->intersend_;
}
inline ::RemyBuffers::OptimizationSetting* OptimizationSettings::mutable_intersend() {
  set_has_intersend();
  if (intersend_ == NULL) intersend_ = new ::RemyBuffers::OptimizationSetting;
  return intersend_;
}
inline ::RemyBuffers::OptimizationSetting* OptimizationSettings::release_intersend() {
  clear_has_intersend();
  ::RemyBuffers::OptimizationSetting* temp = intersend_;
  intersend_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// Range

// optional double low = 61;
inline bool Range::has_low() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Range::set_has_low() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Range::clear_has_low() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Range::clear_low() {
  low_ = 0;
  clear_has_low();
}
inline double Range::low() const {
  return low_;
}
inline void Range::set_low(double value) {
  set_has_low();
  low_ = value;
}

// optional double high = 62;
inline bool Range::has_high() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Range::set_has_high() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Range::clear_has_high() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Range::clear_high() {
  high_ = 0;
  clear_has_high();
}
inline double Range::high() const {
  return high_;
}
inline void Range::set_high(double value) {
  set_has_high();
  high_ = value;
}

// -------------------------------------------------------------------

// ConfigRange

// optional .RemyBuffers.Range link_packets_per_ms = 71;
inline bool ConfigRange::has_link_packets_per_ms() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConfigRange::set_has_link_packets_per_ms() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConfigRange::clear_has_link_packets_per_ms() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConfigRange::clear_link_packets_per_ms() {
  if (link_packets_per_ms_ != NULL) link_packets_per_ms_->::RemyBuffers::Range::Clear();
  clear_has_link_packets_per_ms();
}
inline const ::RemyBuffers::Range& ConfigRange::link_packets_per_ms() const {
  return link_packets_per_ms_ != NULL ? *link_packets_per_ms_ : *default_instance_->link_packets_per_ms_;
}
inline ::RemyBuffers::Range* ConfigRange::mutable_link_packets_per_ms() {
  set_has_link_packets_per_ms();
  if (link_packets_per_ms_ == NULL) link_packets_per_ms_ = new ::RemyBuffers::Range;
  return link_packets_per_ms_;
}
inline ::RemyBuffers::Range* ConfigRange::release_link_packets_per_ms() {
  clear_has_link_packets_per_ms();
  ::RemyBuffers::Range* temp = link_packets_per_ms_;
  link_packets_per_ms_ = NULL;
  return temp;
}

// optional .RemyBuffers.Range rtt = 72;
inline bool ConfigRange::has_rtt() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ConfigRange::set_has_rtt() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ConfigRange::clear_has_rtt() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ConfigRange::clear_rtt() {
  if (rtt_ != NULL) rtt_->::RemyBuffers::Range::Clear();
  clear_has_rtt();
}
inline const ::RemyBuffers::Range& ConfigRange::rtt() const {
  return rtt_ != NULL ? *rtt_ : *default_instance_->rtt_;
}
inline ::RemyBuffers::Range* ConfigRange::mutable_rtt() {
  set_has_rtt();
  if (rtt_ == NULL) rtt_ = new ::RemyBuffers::Range;
  return rtt_;
}
inline ::RemyBuffers::Range* ConfigRange::release_rtt() {
  clear_has_rtt();
  ::RemyBuffers::Range* temp = rtt_;
  rtt_ = NULL;
  return temp;
}

// optional .RemyBuffers.Range num_senders = 73;
inline bool ConfigRange::has_num_senders() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ConfigRange::set_has_num_senders() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ConfigRange::clear_has_num_senders() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ConfigRange::clear_num_senders() {
  if (num_senders_ != NULL) num_senders_->::RemyBuffers::Range::Clear();
  clear_has_num_senders();
}
inline const ::RemyBuffers::Range& ConfigRange::num_senders() const {
  return num_senders_ != NULL ? *num_senders_ : *default_instance_->num_senders_;
}
inline ::RemyBuffers::Range* ConfigRange::mutable_num_senders() {
  set_has_num_senders();
  if (num_senders_ == NULL) num_senders_ = new ::RemyBuffers::Range;
  return num_senders_;
}
inline ::RemyBuffers::Range* ConfigRange::release_num_senders() {
  clear_has_num_senders();
  ::RemyBuffers::Range* temp = num_senders_;
  num_senders_ = NULL;
  return temp;
}

// optional double mean_off_duration = 81;
inline bool ConfigRange::has_mean_off_duration() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ConfigRange::set_has_mean_off_duration() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ConfigRange::clear_has_mean_off_duration() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ConfigRange::clear_mean_off_duration() {
  mean_off_duration_ = 0;
  clear_has_mean_off_duration();
}
inline double ConfigRange::mean_off_duration() const {
  return mean_off_duration_;
}
inline void ConfigRange::set_mean_off_duration(double value) {
  set_has_mean_off_duration();
  mean_off_duration_ = value;
}

// optional double mean_on_duration = 82;
inline bool ConfigRange::has_mean_on_duration() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ConfigRange::set_has_mean_on_duration() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ConfigRange::clear_has_mean_on_duration() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ConfigRange::clear_mean_on_duration() {
  mean_on_duration_ = 0;
  clear_has_mean_on_duration();
}
inline double ConfigRange::mean_on_duration() const {
  return mean_on_duration_;
}
inline void ConfigRange::set_mean_on_duration(double value) {
  set_has_mean_on_duration();
  mean_on_duration_ = value;
}

// -------------------------------------------------------------------

// NetConfig

// optional double mean_on_duration = 1;
inline bool NetConfig::has_mean_on_duration() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NetConfig::set_has_mean_on_duration() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NetConfig::clear_has_mean_on_duration() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NetConfig::clear_mean_on_duration() {
  mean_on_duration_ = 0;
  clear_has_mean_on_duration();
}
inline double NetConfig::mean_on_duration() const {
  return mean_on_duration_;
}
inline void NetConfig::set_mean_on_duration(double value) {
  set_has_mean_on_duration();
  mean_on_duration_ = value;
}

// optional double mean_off_duration = 2;
inline bool NetConfig::has_mean_off_duration() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NetConfig::set_has_mean_off_duration() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NetConfig::clear_has_mean_off_duration() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NetConfig::clear_mean_off_duration() {
  mean_off_duration_ = 0;
  clear_has_mean_off_duration();
}
inline double NetConfig::mean_off_duration() const {
  return mean_off_duration_;
}
inline void NetConfig::set_mean_off_duration(double value) {
  set_has_mean_off_duration();
  mean_off_duration_ = value;
}

// optional uint32 num_senders = 3;
inline bool NetConfig::has_num_senders() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NetConfig::set_has_num_senders() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NetConfig::clear_has_num_senders() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NetConfig::clear_num_senders() {
  num_senders_ = 0u;
  clear_has_num_senders();
}
inline ::google::protobuf::uint32 NetConfig::num_senders() const {
  return num_senders_;
}
inline void NetConfig::set_num_senders(::google::protobuf::uint32 value) {
  set_has_num_senders();
  num_senders_ = value;
}

// optional double link_ppt = 4;
inline bool NetConfig::has_link_ppt() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NetConfig::set_has_link_ppt() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NetConfig::clear_has_link_ppt() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NetConfig::clear_link_ppt() {
  link_ppt_ = 0;
  clear_has_link_ppt();
}
inline double NetConfig::link_ppt() const {
  return link_ppt_;
}
inline void NetConfig::set_link_ppt(double value) {
  set_has_link_ppt();
  link_ppt_ = value;
}

// optional double delay = 5;
inline bool NetConfig::has_delay() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NetConfig::set_has_delay() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NetConfig::clear_has_delay() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NetConfig::clear_delay() {
  delay_ = 0;
  clear_has_delay();
}
inline double NetConfig::delay() const {
  return delay_;
}
inline void NetConfig::set_delay(double value) {
  set_has_delay();
  delay_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace RemyBuffers

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dna_2eproto__INCLUDED
